### ISSUE TITLE
Loren

### ISSUE THREAD

**Issue by kozyulin** [annoyingmouse/gMusic#2]

**Comment by annoyingmouse** [comment]
HI there, what seems to the problem?

**Comment by kozyulin** [comment]
Sorry, can't understand how it works

**Comment by annoyingmouse** [comment]
It just pauses and plays music playing within [Google Music](https://play.google.com/music/) when you're working in a different tab in Chrome or Opera, nothing mind blowing, it just means you don't have to find the tab in order to pause the music playing.  You need to have music playing in the first place as well. That okay?

**Comment by kozyulin** [comment]
Ok. Thank you for assistance. I'll try to manage the rest
